rem dev_appserver.py .\ --history_path=c:\wrook\datastores\current\datastore.history --datastore_path=c:\wrook\datastores\current\datastore
rem dev_appserver.py .\ --history_path=c:\wrook\datastores\full\datastore.history --datastore_path=c:\wrook\datastores\full\datastore

dev_appserver.py .\ -d --enable_sendmail --history_path=c:\wrook\datastores\current\datastore.history --datastore_path=c:\wrook\datastores\current\datastore

